HTTP/2 422 
alt-svc: h3=":9443"; ma=2592000
content-type: application/json
date: Tue, 23 Sep 2025 13:37:29 GMT
server: uvicorn
via: 1.1 Caddy
content-length: 99

{"detail":[{"type":"missing","loc":["body","openai_api_key"],"msg":"Field required","input":null}]}